# Site settings
title: Hitesh's portfolio site
email: khatri.hitesh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my portfoio site where I showcase my work, tech stack and experience I have!!.
url: "https://hitesh97.github.io" # the base hostname & protocol for your site
twitter_username: khatrihitesh97
github_username: hitesh97

# Build settings
# markdown: kramdown
# permalink: /:year/:title:output_ext
theme: jekyll-theme-hacker
